name: Puara-Module Arduino Example CI
on: [push, pull_request]
jobs:
  lint: # Step 1 : Check if repository comformity to Arduino Library standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
            project-type: library
            compliance: strict
            library-manager: submit

  compile: # Step 2: Compile Examples for Multiple Boards
    runs-on: ubuntu-latest
    steps:
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          export PATH=$PATH:$(pwd)/bin
          arduino-cli config init
          arduino-cli core update-index

      # Install Board Cores
      - name: Install ESP32 Core
        run: |
          arduino-cli core install esp32:esp32

      # Compile Example Sketches for Tinypico
      - name: Compile for TinyPICO
        run: |
          arduino-cli compile --fqbn esp32:esp32:tintypico examples/puara_basic_template/puara_basic_template.ino

      # Compile Example Sketches for Xiao ESP32-S3
      - name: Compile for XIAO ESP32-S3
        run: |
          arduino-cli compile --fqbn esp32:esp32:xiao_seeed_s3 examples/puara_basic_template/puara_basic_template.ino
